# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadinfo',
            name='type',
            field=models.CharField(choices=[('tree_canopy', 'Tree Canopy'), ('tree_height', 'Tree Height'), ('primary_forest', 'Primary Forest'), ('forest_gain', 'Forest Gain'), ('forest_loss', 'Forest Loss'), ('forest_extend', 'Forest Extend')], max_length=50),
        ),
    ]
