class DownloadLink:
    def get_download_link_lc(self, country, year):
        if country == 'Myanmar':
            # Dictionary containing download links mapped by year
            file_links_by_year = {
                2000: 'https://drive.google.com/file/d/16fQrdEK4OTTR9iOfkgZetswJSudBEc2C/view?usp=drive_link',
                2001: 'https://drive.google.com/file/d/1FGLIghgPqwn1ZTLGNQ9fxWNqeNKjo6vY/view?usp=drive_link',
                2002: 'https://drive.google.com/file/d/1GlEneHKZtfoYJgDUpCJY326X6XRxn925/view?usp=drive_link',
                2003: 'https://drive.google.com/file/d/11AU5lqETg4OEyC6w5ZxhyMj4KFi1HvUF/view?usp=drive_link',
                2004: 'https://drive.google.com/file/d/13kyz6C0OTQaxhFo5cZB0t96POgw7Apu9/view?usp=drive_link',
                2005: 'https://drive.google.com/file/d/1v2CW_klS8_3YowAfcdPraC1c0fA2nDwM/view?usp=drive_link',
                2006: 'https://drive.google.com/file/d/1fuXnc6vzayeENCCN0fHzzJudIX231EKi/view?usp=drive_link',
                2007: 'https://drive.google.com/file/d/1huaEwoCUSzwLeyM2sH5Zz_2YhYcuHiVx/view?usp=drive_link',
                2008: 'https://drive.google.com/file/d/12IbzzPv7aHooTj2eHhMc3FAZagbKifhp/view?usp=drive_link',
                2009: 'https://drive.google.com/file/d/1Yw9p-aM00-Z9S5wfDkxA-P8Xj8aFuSlw/view?usp=drive_link',
                2010: 'https://drive.google.com/file/d/1_QFrrSRVBaA_S59GyHcEQhfABsmhxSsn/view?usp=drive_link',
                2011: 'https://drive.google.com/file/d/19VPRP2r5cwlH2hTSI6rknv_vEca12yfj/view?usp=drive_link',
                2012: 'https://drive.google.com/file/d/1_N1go0QShNSVv2z6cm7Ge7Kn6PhcNzcs/view?usp=drive_link',
                2013: 'https://drive.google.com/file/d/1KtoTUJI9q1YhLZSl6HVfFJDrScK4G3NA/view?usp=drive_link',
                2014: 'https://drive.google.com/file/d/1PAigD_kjey_oEgwBWqnxnnvZO50ejkIA/view?usp=drive_link',
                2015: 'https://drive.google.com/file/d/1vXjNXTvOYE_G0OhHHjiDlufNcybulFu4/view?usp=drive_link',
                2016: 'https://drive.google.com/file/d/1mSj96NhZXvvmRYbajcqn2t6x-zHEMfLR/view?usp=drive_link',
                2017: 'https://drive.google.com/file/d/1_mWgzvdwpAUVFCitGrS1Uo20zW1SXlzC/view?usp=drive_link',
                2018: 'https://drive.google.com/file/d/1G8RacPxRbfcjCXFsEuGq4CPamva4g-hw/view?usp=drive_link',
                2019: 'https://drive.google.com/file/d/13UN6iONtPuIFzvLX-F-0EyDKiquz1cCM/view?usp=drive_link',
                2020: 'https://drive.google.com/file/d/1_Up9ar_m3km8KOMsND5WQ7vSJtjA_7TE/view?usp=drive_link',
                2021: 'https://drive.google.com/file/d/1TCUMQV4rO_lll8rm8-XpLjveFJkc8R2k/view?usp=drive_link',
                2022: 'https://drive.google.com/file/d/1lJrv6q-cEUxhTaoL9T34cR0TNaskQql-/view?usp=drive_link',
                2023: 'https://drive.google.com/file/d/1aOun8fSOCTh5NCY3Imb4RGhPkLIN0kvB/view?usp=drive_link',
            }
        elif country == 'Thailand':
            file_links_by_year = {
                2000: 'https://drive.google.com/file/d/1_XK-gvVK-126E2nOUwyqrsNTQBPySCGh/view?usp=drive_link',
                2001: 'https://drive.google.com/file/d/1V-WwYOxwoR-2K2gveBi5h7ZcqBqoiMDe/view?usp=drive_link',
                2002: 'https://drive.google.com/file/d/14VeYPylnzteakWTcaRgK3r6s--4jawO-/view?usp=drive_link',
                2003: 'https://drive.google.com/file/d/1vpOz6hDv4oCmBct0IzWF90CNgZZ5jMx2/view?usp=drive_link',
                2004: 'https://drive.google.com/file/d/1Pibc_3awJzZs5hgeYuJJH6A2gsAan7UQ/view?usp=drive_link',
                2005: 'https://drive.google.com/file/d/1f1PUQ8sL3o0XAa8ovrgRHd-zHUbjwWkq/view?usp=drive_link',
                2006: 'https://drive.google.com/file/d/1PgATw3gfEQmY42f8-ltLGi-m6Kq3L2ql/view?usp=drive_link',
                2007: 'https://drive.google.com/file/d/1rfo2-t84Rzi-7ASoMLPR1pgTid3Am3VR/view?usp=drive_link',
                2008: 'https://drive.google.com/file/d/1A8GRI7QNStmqan_dzaNOfEucGvkHgb-S/view?usp=drive_link',
                2009: 'https://drive.google.com/file/d/1XoetBoAOYaacwWyh4fhi6ovOimsHN-Om/view?usp=drive_link',
                2010: 'https://drive.google.com/file/d/1HO5Fo0uc3OBpHucCjBNZmG7-20_rPVF1/view?usp=drive_link',
                2011: 'https://drive.google.com/file/d/18-t36sxlpJbuf2-7fsQASVvwO82labdp/view?usp=drive_link',
                2012: 'https://drive.google.com/file/d/1gEbfyjVqC_V1Gmmkbld1qKiw7xOqbiFp/view?usp=drive_link',
                2013: 'https://drive.google.com/file/d/184E4abDo2hPcTjvWZvZ9EGh9n0j6bXm9/view?usp=drive_link',
                2014: 'https://drive.google.com/file/d/1QluIM8G6NkN7E06i7x4UwHMsBdNPAlAs/view?usp=drive_link',
                2015: 'https://drive.google.com/file/d/1SSf2yN118FxumcSKulMQOVD5iasMeFK_/view?usp=drive_link',
                2016: 'https://drive.google.com/file/d/1ebSEtbyUk1vKZ86k4wYSCEFdNWA_CL6Z/view?usp=drive_link',
                2017: 'https://drive.google.com/file/d/1z6O13XbLas0KknVM5TqK77gzfI354qm8/view?usp=drive_link',
                2018: 'https://drive.google.com/file/d/1aHAlTVKBnn5QAWCmsMSTVu2gB80_EWCD/view?usp=drive_link',
                2019: 'https://drive.google.com/file/d/1jx8zapb0EgD11TYbznmt6_aIT8E4sF0D/view?usp=drive_link',
                2020: 'https://drive.google.com/file/d/1_p_U87Wf3esK-2RrFsg6eVvDB4__NqcD/view?usp=drive_link',
                2021: 'https://drive.google.com/file/d/1X7FQZHIdGpcoj0AlR6cOtb849przvRMF/view?usp=drive_link',
                2022: 'https://drive.google.com/file/d/14lo6dvtRZATOp-PAGh-FkWzDU0MVVNwA/view?usp=drive_link',
                2023: 'https://drive.google.com/file/d/17Xk2wmqSbbXXBgho4brspHJg6HBKwgoW/view?usp=drive_link',
            }
        elif country == 'Vietnam':
            file_links_by_year = {
                2000: 'https://drive.google.com/file/d/16Wi4GTgAYbWlJagb2N7Bsa7Nayh7dCLR/view?usp=drive_link',
                2001: 'https://drive.google.com/file/d/1SB_fhs8snTTFiRyWvn3GasMZF2UY4K8V/view?usp=drive_link',
                2002: 'https://drive.google.com/file/d/1QwXSUn1iEtWiutYmgjr45JWhD4j0ej5s/view?usp=drive_link',
                2003: 'https://drive.google.com/file/d/1K4SAezV1-NZehF1fwwnKpkAwQOWtBJo5/view?usp=drive_link',
                2004: 'https://drive.google.com/file/d/1q_hvR8KImGGou68KSUpRvxRRZ-ZUkcA0/view?usp=drive_link',
                2005: 'https://drive.google.com/file/d/15-0RwciTS5hZ8vma-2oyZc7qPolKl9LS/view?usp=drive_link',
                2006: 'https://drive.google.com/file/d/1s_aJas4rm2oBj0uTEgn9ywlf3KUMZ8SR/view?usp=drive_link',
                2007: 'https://drive.google.com/file/d/1ICMX1ygEFWwEzDPTnPXlUeK6X64fzLwu/view?usp=drive_link',
                2008: 'https://drive.google.com/file/d/1Cj_Re2bgEowPXPVMPmeu5IRXIUHZgZcU/view?usp=drive_link',
                2009: 'https://drive.google.com/file/d/1G-BxLRDsgGKc5XqO2zLfsQXgtdjSHH7N/view?usp=drive_link',
                2010: 'https://drive.google.com/file/d/1nHlg9JHRESggwjl6ghh79_KKcH6cRkia/view?usp=drive_link',
                2011: 'https://drive.google.com/file/d/12ANc6WZxhdoQllL2K8vEhaYltSz6Qk4S/view?usp=drive_link',
                2012: 'https://drive.google.com/file/d/1XLJqfotkYmECbYT0jGHr7fg6svT9yuiY/view?usp=drive_link',
                2013: 'https://drive.google.com/file/d/1G3wXC2KYCsN-3eGrXcT7AQda8lvvEcdM/view?usp=drive_link',
                2014: 'https://drive.google.com/file/d/1A-w_uT-kIIQoiyC1jLBeCl-_1IX55GdH/view?usp=drive_link',
                2015: 'https://drive.google.com/file/d/1PiRRwTYW4Jj-neX-tUO6wzBRh85LJJ-1/view?usp=drive_link',
                2016: 'https://drive.google.com/file/d/12s9GR3vrdQaybPJJ7X_yP7GSjJ65qQO-/view?usp=drive_link',
                2017: 'https://drive.google.com/file/d/1rBXJvRZS9Bged7izyjNGU4zgkr7KR6Ig/view?usp=drive_link',
                2018: 'https://drive.google.com/file/d/1NEKsAoGesQc-LcQ_WAZm8ScNXhcnyZgT/view?usp=drive_link',
                2019: 'https://drive.google.com/file/d/12bR-MIfZ_A8ZkiCtryH3_yD1Ux8SVeqi/view?usp=drive_link',
                2020: 'https://drive.google.com/file/d/1qoHjLKXgEZfCFzjeBl5cKfB-QW9wg4aY/view?usp=drive_link',
                2021: 'https://drive.google.com/file/d/18iRfX_fxVhPHWz2rrY8vu-946x4drxta/view?usp=drive_link',
                2022: 'https://drive.google.com/file/d/1IkO5TPLO-Utx5UwJ9FfRsugeC7ajo778/view?usp=drive_link',
                2023: 'https://drive.google.com/file/d/1rVvN-3ZvLGwXr7-0KDv8Lnxc80FLcVUV/view?usp=drive_link',
            }
        elif country == 'Cambodia':
            file_links_by_year = {
                2000: 'https://drive.google.com/file/d/1gpUgggkgHkAPLd8HxwwBcheyt3G0oRHP/view?usp=drive_link',
                2001: 'https://drive.google.com/file/d/1nLe0RXu0MeARJXRUOspaCsX5B8Jt82AR/view?usp=drive_link',
                2002: 'https://drive.google.com/file/d/1-Dwibo1Z0fNKwS22DcJJgl01KxBS9lM2/view?usp=drive_link',
                2003: 'https://drive.google.com/file/d/1HVPUCe0ifO3UGnMRcnlCOihMb8hcwp9N/view?usp=drive_link',
                2004: 'https://drive.google.com/file/d/1Y9IYgerMACHZuro5-F7F3-_3552Yxu_C/view?usp=drive_link',
                2005: 'https://drive.google.com/file/d/1Qx4HxZVVHNrCEhf13jXZHJBDiAqQSiCc/view?usp=drive_link',
                2006: 'https://drive.google.com/file/d/1iOgmO-_Wy26goXjbiyuY_f0R5LcWlLCa/view?usp=drive_link',
                2007: 'https://drive.google.com/file/d/1lbiSCwWk5yhMZ-G9_mNq1_oaX04U5Pe4/view?usp=drive_link',
                2008: 'https://drive.google.com/file/d/1kr60vwB3syw0Wi9kvGEQlrCfltODDczK/view?usp=drive_link',
                2009: 'https://drive.google.com/file/d/16nVQAfWQF1swVB9oiDLYVyFNL4mT9Sxo/view?usp=drive_link',
                2010: 'https://drive.google.com/file/d/1OYrGJicNXY0E8eAqs7ztWYtzS1cLAFBJ/view?usp=drive_link',
                2011: 'https://drive.google.com/file/d/1hFsNbR-GyuXa4HyWAchfo29oWl_qdbdf/view?usp=drive_link',
                2012: 'https://drive.google.com/file/d/17oFEQ-Gg59-n4ZrRVHcosFaQ9msuwC1Z/view?usp=drive_link',
                2013: 'https://drive.google.com/file/d/1gbQvBGLCX06zxrp06ctBBodZsvdVkl6c/view?usp=drive_link',
                2014: 'https://drive.google.com/file/d/1zpS1gMFQbGJ73ZxXYCMSffcJg-Lp3qvc/view?usp=drive_link',
                2015: 'https://drive.google.com/file/d/1NgVPoRV0S8ylRmstJRqTaXbuRJIR4BDp/view?usp=drive_link',
                2016: 'https://drive.google.com/file/d/1Wbi6jZMDYSEm3WavwIxQhtFZurAQGouD/view?usp=drive_link',
                2017: 'https://drive.google.com/file/d/1s8SErG6HAN5klTVt_X45ygDs23uCW7Rf/view?usp=drive_link',
                2018: 'https://drive.google.com/file/d/1KRFSkj2ipSER1pgVbmBgPgmJp8DpTXmg/view?usp=drive_link',
                2019: 'https://drive.google.com/file/d/1VN_MupFgRsWXWjyxQdX7V9PseT4cxbow/view?usp=drive_link',
                2020: 'https://drive.google.com/file/d/11bvx8J5oVgXWUcdi-7-nWvCFDcAjaQoz/view?usp=drive_link',
                2021: 'https://drive.google.com/file/d/1bmhs9GIQayUAALYdQ8lLBgfGJL-XU0uU/view?usp=drive_link',
                2022: 'https://drive.google.com/file/d/1aCJQdw2n-F1yfsEIK7SGpdZaC9NRRH6r/view?usp=drive_link',
                2023: 'https://drive.google.com/file/d/1yVg_fcxFuq20p_UbANqVymIa8j1_31ZV/view?usp=drive_link',
            }
        elif country == 'Laos':
            file_links_by_year = {
                2000: 'https://drive.google.com/file/d/1xkh-GkQqM78bdLTGKpX4sh10oscLuHnW/view?usp=drive_link',
                2001: 'https://drive.google.com/file/d/1Xg_qrurLbTyOITtLkng8OVctmQXWgwuh/view?usp=drive_link',
                2002: 'https://drive.google.com/file/d/1wScbYilFydJsqmYoT6vgthOnwLPWPLG6/view?usp=drive_link',
                2003: 'https://drive.google.com/file/d/10RQeUG_dumYMHOCSC_akfzX2MrT5SRYt/view?usp=drive_link',
                2004: 'https://drive.google.com/file/d/1XaOHO2G4pFXJpYwoaKDfgV8CN00gErmz/view?usp=drive_link',
                2005: 'https://drive.google.com/file/d/1fnzrvH6cgR_bFq-Qj2DGobvqt8t_ny3G/view?usp=drive_link',
                2006: 'https://drive.google.com/file/d/1YW4rTXUb-lKzRJXcO_9j411Iy7OV43Z-/view?usp=drive_link',
                2007: 'https://drive.google.com/file/d/1Rc6ZvSLtnH2vcEZCsGPvQdAz1q3S6bJo/view?usp=drive_link',
                2008: 'https://drive.google.com/file/d/1XWFg3BctypgTeJCZqpphTmLaScQc1V1r/view?usp=drive_link',
                2009: 'https://drive.google.com/file/d/1m-CTNd9VlfEDrPVWxN6mHkcx19Z-XjXn/view?usp=drive_link',
                2010: 'https://drive.google.com/file/d/1Nr0brpldfvE9t3J-HUyJAjJYlzo3OtN1/view?usp=drive_link',
                2011: 'https://drive.google.com/file/d/13vC-lUyHlOgh8r35fOZPX6efJvX2gsty/view?usp=drive_link',
                2012: 'https://drive.google.com/file/d/1CwEWDvfbLeimzmkk6N2C1uxhaehuzb1h/view?usp=drive_link',
                2013: 'https://drive.google.com/file/d/1DUkY1KV0mGhREfI2Vyk2NxQWzZuV_6xi/view?usp=drive_link',
                2014: 'https://drive.google.com/file/d/1eiztJqQ4agc77Cdz2GKRoyIXXAPibjcV/view?usp=drive_link',
                2015: 'https://drive.google.com/file/d/159G_EIUYskiqxSQGhA_jVn1qPzYxbwRa/view?usp=drive_link',
                2016: 'https://drive.google.com/file/d/1ITWY87KuolyzTC76nHr6zaMnsnMNpMAp/view?usp=drive_link',
                2017: 'https://drive.google.com/file/d/15OSpEPPg3XUyxnLwwFHyBW_1lDjWoUIp/view?usp=drive_link',
                2018: 'https://drive.google.com/file/d/1-DXHgTF84HKZoBVuKLoRc78v_i3sBHv4/view?usp=drive_link',
                2019: 'https://drive.google.com/file/d/1HVVeZkXPHQ_z9zsMaueP5P73unVqzjlD/view?usp=drive_link',
                2020: 'https://drive.google.com/file/d/1twnVbBTMFHRO6nh6fWnHegKnvs1umZGf/view?usp=drive_link',
                2021: 'https://drive.google.com/file/d/1MeBmeYQlUcE-QLmTbN7T_JfgJhS_OPJA/view?usp=drive_link',
                2022: 'https://drive.google.com/file/d/1uFRKu9H3mgu90I0qqfLa4cj3eAwiDOtV/view?usp=drive_link',
                2023: 'https://drive.google.com/file/d/1VKyZgx1qpi9IS3z0pKn3k8BUsE9iN5yO/view?usp=drive_link',
            }
        
        # Return the download link for the specified year
        return file_links_by_year.get(year)

    