# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-10-01 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('dataset', models.CharField(max_length=100)),
                ('purpose_of_download', models.TextField()),
                ('downloaded_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Downloaded User Info',
            },
        ),
    ]
